/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasActividades;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import vistasPrincipales.Ejercicios1;

/**
 *
 * @author valkiria
 */
public class ToBeQuestions extends javax.swing.JFrame {

    private ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/pizarronVerde3.jpg"));
    private Image img = icon.getImage();
    
    private ArrayList<JButton> cs;
    private ArrayList<JTextField> es;
    private ArrayList<JButton> crs;
    private ArrayList<JTextField> rs;
    private ArrayList<JLabel> ps;
    
    private int correctas = 0;
    private int incorrectas = 0;
    private double nota = 0.0;
    private double puntajeXEjer=100d / 16d;
    
    private ImageIcon iconNegativo = new ImageIcon(getClass().getResource("/imagenes/cruzRoja2.png"));
    
    /**
     * Creates new form ToBe
     */
    public ToBeQuestions() {
        initComponents();
        
        cs = new ArrayList<>();
        es = new ArrayList<>();

        crs = new ArrayList<>();
        rs = new ArrayList<>();
        ps=new ArrayList<>();

        cs.add(c1);
        cs.add(c2);
        cs.add(c3);
        cs.add(c4);
        cs.add(c5);
        cs.add(c6);
        cs.add(c7);
        cs.add(c9);
        cs.add(c10);
        cs.add(c11);
       
        crs.add(cr1);
        crs.add(cr2);
        crs.add(cr3);
        crs.add(cr4);
        crs.add(cr51);
        crs.add(cr52);
        crs.add(cr6);
        crs.add(cr7);
        crs.add(cr9);
        crs.add(cr10);
        crs.add(cr11);
        
        es.add(e1);
        es.add(e2);
        es.add(e3);
        es.add(e4);
        es.add(e4);
        es.add(e5);
        es.add(e6);
        es.add(e7);
        es.add(e8);
        es.add(e9);
        es.add(e10);
        es.add(e11);

        ps.add(p1);
        ps.add(p2);
        ps.add(p3);
        ps.add(p4);
        ps.add(p4);
        ps.add(p5);
        ps.add(p6);
        ps.add(p7);
        ps.add(p8);
        ps.add(p9);
        ps.add(p10);
        ps.add(p11);
        
        rs.add(e1);
        rs.add(e2);
        rs.add(e3);
        rs.add(e4);
        rs.add(e4);
        rs.add(e5);
        rs.add(e6);
        rs.add(e7);
        rs.add(e8);
        rs.add(e9);
        rs.add(e10);
        rs.add(e11);

        for (JButton c : cs) {
            c.setVisible(false);
        }
        
        crs.forEach(cr->{
            cr.setContentAreaFilled(false);
            cr.setVisible(false);
                });
        this.setLocationRelativeTo(null);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel31 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        e6 = new javax.swing.JTextField();
        r7 = new javax.swing.JTextField();
        e7 = new javax.swing.JTextField();
        e8 = new javax.swing.JTextField();
        p11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        e11 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        p1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        e4 = new javax.swing.JTextField();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        r4 = new javax.swing.JTextField();
        e5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        r6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        textoCorrectas = new javax.swing.JLabel();
        textoIncorrectas = new javax.swing.JLabel();
        textoNota = new javax.swing.JLabel();
        botonCorregir = new javax.swing.JButton();
        botonReiniciar = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        cr4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        cr51 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        cr1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        cr2 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        r3 = new javax.swing.JTextField();
        cr3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        r52 = new javax.swing.JTextField();
        cr6 = new javax.swing.JButton();
        r51 = new javax.swing.JTextField();
        cr52 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        cr7 = new javax.swing.JButton();
        r8 = new javax.swing.JTextField();
        cr8 = new javax.swing.JButton();
        e9 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        c9 = new javax.swing.JButton();
        cr9 = new javax.swing.JButton();
        r9 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        e10 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        c10 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        r10 = new javax.swing.JTextField();
        cr10 = new javax.swing.JButton();
        r11 = new javax.swing.JTextField();
        cr11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(0, 255, 51));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 0));
        jLabel31.setText("Complete the sentences with the correct form of the verb TO BE, and after response the questions.");

        p7.setBackground(new java.awt.Color(255, 255, 255));
        p7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 255, 255));
        p7.setText("mica and pedro ");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("yes,");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("no,");

        e6.setBackground(new java.awt.Color(39, 82, 156));
        e6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e6.setForeground(new java.awt.Color(255, 255, 102));

        r7.setBackground(new java.awt.Color(39, 82, 156));
        r7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r7.setForeground(new java.awt.Color(255, 255, 102));

        e7.setBackground(new java.awt.Color(39, 82, 156));
        e7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e7.setForeground(new java.awt.Color(255, 255, 102));

        e8.setBackground(new java.awt.Color(39, 82, 156));
        e8.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e8.setForeground(new java.awt.Color(255, 255, 102));
        e8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e8ActionPerformed(evt);
            }
        });

        p11.setBackground(new java.awt.Color(255, 255, 255));
        p11.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p11.setForeground(new java.awt.Color(255, 255, 255));
        p11.setText("your");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" playing video games?.");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("yes,");

        e11.setBackground(new java.awt.Color(39, 82, 156));
        e11.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e11.setForeground(new java.awt.Color(255, 255, 102));
        e11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e11ActionPerformed(evt);
            }
        });

        e1.setBackground(new java.awt.Color(39, 82, 156));
        e1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 255, 102));

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("nicolas");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("a good student?.");

        p4.setBackground(new java.awt.Color(255, 255, 255));
        p4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 255, 255));
        p4.setText("you and i ");

        e2.setBackground(new java.awt.Color(39, 82, 156));
        e2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 255, 102));

        e3.setBackground(new java.awt.Color(39, 82, 156));
        e3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 255, 102));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("yes, ");

        e4.setBackground(new java.awt.Color(39, 82, 156));
        e4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e4.setForeground(new java.awt.Color(255, 255, 102));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("my sister");

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setText("I ");

        r4.setBackground(new java.awt.Color(39, 82, 156));
        r4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r4.setForeground(new java.awt.Color(255, 255, 102));

        e5.setBackground(new java.awt.Color(39, 82, 156));
        e5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e5.setForeground(new java.awt.Color(255, 255, 102));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("yes, ");

        r6.setBackground(new java.awt.Color(39, 82, 156));
        r6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r6.setForeground(new java.awt.Color(255, 255, 102));
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" in secundary now?");

        p6.setBackground(new java.awt.Color(255, 255, 255));
        p6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p6.setForeground(new java.awt.Color(255, 255, 255));
        p6.setText("Gisela and tamara");

        textoCorrectas.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        textoCorrectas.setForeground(new java.awt.Color(255, 255, 255));
        textoCorrectas.setText("  ");

        textoIncorrectas.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        textoIncorrectas.setForeground(new java.awt.Color(255, 255, 255));
        textoIncorrectas.setText("  ");

        textoNota.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        textoNota.setForeground(new java.awt.Color(255, 255, 255));
        textoNota.setText("  ");

        botonCorregir.setText("CORREGIR");
        botonCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorregirActionPerformed(evt);
            }
        });

        botonReiniciar.setText("REINICIAR");
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });

        c1.setBackground(new java.awt.Color(153, 153, 153));
        c1.setForeground(new java.awt.Color(153, 153, 153));
        c1.setBorder(null);
        c1.setBorderPainted(false);
        c1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        c2.setBackground(new java.awt.Color(153, 153, 153));
        c2.setForeground(new java.awt.Color(153, 153, 153));
        c2.setBorder(null);
        c2.setBorderPainted(false);
        c2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setBackground(new java.awt.Color(153, 153, 153));
        c3.setForeground(new java.awt.Color(153, 153, 153));
        c3.setBorder(null);
        c3.setBorderPainted(false);
        c3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c4.setBackground(new java.awt.Color(153, 153, 153));
        c4.setForeground(new java.awt.Color(153, 153, 153));
        c4.setBorder(null);
        c4.setBorderPainted(false);
        c4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        cr4.setBackground(new java.awt.Color(153, 153, 153));
        cr4.setForeground(new java.awt.Color(153, 153, 153));
        cr4.setBorder(null);
        cr4.setBorderPainted(false);
        cr4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr4ActionPerformed(evt);
            }
        });

        c5.setBackground(new java.awt.Color(153, 153, 153));
        c5.setForeground(new java.awt.Color(153, 153, 153));
        c5.setBorder(null);
        c5.setBorderPainted(false);
        c5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        cr51.setBackground(new java.awt.Color(153, 153, 153));
        cr51.setForeground(new java.awt.Color(153, 153, 153));
        cr51.setBorder(null);
        cr51.setBorderPainted(false);
        cr51.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr51ActionPerformed(evt);
            }
        });

        c6.setBackground(new java.awt.Color(153, 153, 153));
        c6.setForeground(new java.awt.Color(153, 153, 153));
        c6.setBorder(null);
        c6.setBorderPainted(false);
        c6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        c8.setBackground(new java.awt.Color(153, 153, 153));
        c8.setForeground(new java.awt.Color(153, 153, 153));
        c8.setBorder(null);
        c8.setBorderPainted(false);
        c8.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });

        c11.setBackground(new java.awt.Color(153, 153, 153));
        c11.setForeground(new java.awt.Color(153, 153, 153));
        c11.setBorder(null);
        c11.setBorderPainted(false);
        c11.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flechita1.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(225, 225, 225));
        jLabel33.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(225, 225, 225));
        jLabel33.setText("yes, ");

        r1.setBackground(new java.awt.Color(39, 82, 156));
        r1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 102));

        cr1.setBackground(new java.awt.Color(153, 153, 153));
        cr1.setForeground(new java.awt.Color(153, 153, 153));
        cr1.setBorder(null);
        cr1.setBorderPainted(false);
        cr1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel34.setBackground(new java.awt.Color(225, 225, 225));
        jLabel34.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(225, 225, 225));
        jLabel34.setText("no, ");

        r2.setBackground(new java.awt.Color(39, 82, 156));
        r2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 102));
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        cr2.setBackground(new java.awt.Color(153, 153, 153));
        cr2.setForeground(new java.awt.Color(153, 153, 153));
        cr2.setBorder(null);
        cr2.setBorderPainted(false);
        cr2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel35.setBackground(new java.awt.Color(225, 225, 225));
        jLabel35.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(225, 225, 225));
        jLabel35.setText("no, ");

        r3.setBackground(new java.awt.Color(39, 82, 156));
        r3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 255, 102));
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        cr3.setBackground(new java.awt.Color(153, 153, 153));
        cr3.setForeground(new java.awt.Color(153, 153, 153));
        cr3.setBorder(null);
        cr3.setBorderPainted(false);
        cr3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("no, ");

        r52.setBackground(new java.awt.Color(39, 82, 156));
        r52.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r52.setForeground(new java.awt.Color(255, 255, 102));
        r52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r52ActionPerformed(evt);
            }
        });

        cr6.setBackground(new java.awt.Color(153, 153, 153));
        cr6.setForeground(new java.awt.Color(153, 153, 153));
        cr6.setBorder(null);
        cr6.setBorderPainted(false);
        cr6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr6ActionPerformed(evt);
            }
        });

        r51.setBackground(new java.awt.Color(39, 82, 156));
        r51.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r51.setForeground(new java.awt.Color(255, 255, 102));
        r51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r51ActionPerformed(evt);
            }
        });

        cr52.setBackground(new java.awt.Color(153, 153, 153));
        cr52.setForeground(new java.awt.Color(153, 153, 153));
        cr52.setBorder(null);
        cr52.setBorderPainted(false);
        cr52.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr52ActionPerformed(evt);
            }
        });

        c7.setBackground(new java.awt.Color(153, 153, 153));
        c7.setForeground(new java.awt.Color(153, 153, 153));
        c7.setBorder(null);
        c7.setBorderPainted(false);
        c7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        cr7.setBackground(new java.awt.Color(153, 153, 153));
        cr7.setForeground(new java.awt.Color(153, 153, 153));
        cr7.setBorder(null);
        cr7.setBorderPainted(false);
        cr7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr7ActionPerformed(evt);
            }
        });

        r8.setBackground(new java.awt.Color(39, 82, 156));
        r8.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r8.setForeground(new java.awt.Color(255, 255, 102));

        cr8.setBackground(new java.awt.Color(153, 153, 153));
        cr8.setForeground(new java.awt.Color(153, 153, 153));
        cr8.setBorder(null);
        cr8.setBorderPainted(false);
        cr8.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr8ActionPerformed(evt);
            }
        });

        e9.setBackground(new java.awt.Color(39, 82, 156));
        e9.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e9.setForeground(new java.awt.Color(255, 255, 102));
        e9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e9ActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("in the rosario city?.");

        c9.setBackground(new java.awt.Color(153, 153, 153));
        c9.setForeground(new java.awt.Color(153, 153, 153));
        c9.setBorder(null);
        c9.setBorderPainted(false);
        c9.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });

        cr9.setBackground(new java.awt.Color(153, 153, 153));
        cr9.setForeground(new java.awt.Color(153, 153, 153));
        cr9.setBorder(null);
        cr9.setBorderPainted(false);
        cr9.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr9ActionPerformed(evt);
            }
        });

        r9.setBackground(new java.awt.Color(39, 82, 156));
        r9.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r9.setForeground(new java.awt.Color(255, 255, 102));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("no,");

        e10.setBackground(new java.awt.Color(39, 82, 156));
        e10.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        e10.setForeground(new java.awt.Color(255, 255, 102));
        e10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e10ActionPerformed(evt);
            }
        });

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" in the oliveros town?.");

        c10.setBackground(new java.awt.Color(153, 153, 153));
        c10.setForeground(new java.awt.Color(153, 153, 153));
        c10.setBorder(null);
        c10.setBorderPainted(false);
        c10.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("yes,");

        r10.setBackground(new java.awt.Color(39, 82, 156));
        r10.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r10.setForeground(new java.awt.Color(255, 255, 102));

        cr10.setBackground(new java.awt.Color(153, 153, 153));
        cr10.setForeground(new java.awt.Color(153, 153, 153));
        cr10.setBorder(null);
        cr10.setBorderPainted(false);
        cr10.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr10ActionPerformed(evt);
            }
        });

        r11.setBackground(new java.awt.Color(39, 82, 156));
        r11.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        r11.setForeground(new java.awt.Color(255, 255, 102));

        cr11.setBackground(new java.awt.Color(153, 153, 153));
        cr11.setForeground(new java.awt.Color(153, 153, 153));
        cr11.setBorder(null);
        cr11.setBorderPainted(false);
        cr11.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cr11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" busy?.");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   bad student?.");

        jlabel.setBackground(new java.awt.Color(255, 255, 255));
        jlabel.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("approved?.");

        p5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p5.setForeground(new java.awt.Color(255, 255, 255));
        p5.setText("I");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("your sisters?.");

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("cooking cookies?.");

        p8.setBackground(new java.awt.Color(255, 255, 255));
        p8.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p8.setForeground(new java.awt.Color(255, 255, 255));
        p8.setText("they");

        p9.setBackground(new java.awt.Color(255, 255, 255));
        p9.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p9.setForeground(new java.awt.Color(255, 255, 255));
        p9.setText("we");

        p10.setBackground(new java.awt.Color(255, 255, 255));
        p10.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        p10.setForeground(new java.awt.Color(255, 255, 255));
        p10.setText("we");

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("  bed soft?");

        desktop.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(textoCorrectas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(textoIncorrectas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(textoNota, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(botonCorregir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(botonReiniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr51, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r52, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r51, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr52, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(e10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(c10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(r11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(cr11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jlabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(p10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jButton5)
                                .addGap(212, 212, 212)
                                .addComponent(botonReiniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCorregir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(desktopLayout.createSequentialGroup()
                                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(desktopLayout.createSequentialGroup()
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(r51, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cr51, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(desktopLayout.createSequentialGroup()
                                                                .addComponent(e4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(p4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jlabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(36, 36, 36))
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cr4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(10, 10, 10)
                                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                                                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(r9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(cr9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(r10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cr10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                                .addComponent(e11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(p11)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel41)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addComponent(e9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(21, 21, 21)
                                                        .addComponent(p9)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel37)
                                                        .addGap(41, 41, 41)
                                                        .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addComponent(e10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(p10)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel39)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addComponent(e5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addGap(350, 350, 350)
                                                .addComponent(jLabel28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(r11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cr11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(p3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                        .addComponent(jLabel35)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cr3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(605, 605, 605))
                                    .addGroup(desktopLayout.createSequentialGroup()
                                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addComponent(jLabel33)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r1))
                                                    .addGroup(desktopLayout.createSequentialGroup()
                                                        .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(p1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel2)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cr1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cr2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(p2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addGap(19, 19, 19)
                                                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(desktopLayout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(r52, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cr52, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(35, 35, 35)
                                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(r7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cr7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(570, 570, 570))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cr8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                        .addComponent(e8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(p8)
                                                        .addGap(9, 9, 9)
                                                        .addComponent(jLabel27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                        .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(16, 16, 16)
                                                        .addComponent(cr6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                        .addComponent(e6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(p6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel19)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, desktopLayout.createSequentialGroup()
                                                        .addComponent(e7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(p7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoCorrectas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoIncorrectas, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel31)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p1)
                                .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGap(15, 15, 15)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cr1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cr2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(3, 3, 3)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(cr3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(e6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p6)
                                .addComponent(jLabel19)))
                        .addGap(10, 10, 10)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cr6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p7)
                                .addComponent(e7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label))
                            .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addComponent(cr7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(e8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27)
                                .addComponent(p8))
                            .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(cr8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(textoCorrectas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoIncorrectas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(p4)
                                        .addComponent(e4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlabel))
                                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cr4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(e5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(r51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cr51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cr52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(e9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p9)))
                                    .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(r9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel38))
                                    .addComponent(cr9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(e10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel39)
                                        .addComponent(p10))
                                    .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(r10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel40))
                                    .addComponent(cr10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(e11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p11)
                                        .addComponent(jLabel41))
                                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(r11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cr11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonReiniciar)
                                    .addComponent(botonCorregir)))
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton5)))
                        .addGap(108, 108, 108))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e11ActionPerformed

    private void e8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e8ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void botonCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorregirActionPerformed
        nota = 0.0;
        correctas = 0;
        incorrectas = 0;
        for (int j = 0; j < es.size(); j++) {
            JTextField e = es.get(j);
            if (j == 1 - 1 || j == 2 - 1 || j==11-1) {
                comprobar(e, j, "is");
            } else if (j == 6 - 1 || j == 7 - 1 || j == 8 - 1 || j == 9 - 1 || j == 10 - 1 || j == 4 - 1) {
                comprobar(e, j, "are");
            } else {
                comprobar(e, j, "am");
            }
        }
        
        for (int i = 0; i < rs.size(); i++) {
            JTextField r = rs.get(i);
            if (i == 1 - 1 || i == 2 - 1 || i==11-1) {
               
                comprobarRespuestas(r, i, "is",ps.get(i).getText());
            } else if (i == 6 - 1 || i == 7 - 1 || i == 8 - 1 || i == 9 - 1 || i == 10 - 1 || i == 4 - 1) {
                comprobarRespuestas(r, i, "are",ps.get(i).getText());
            } else {
                if(i==5){
                    comprobarRespuestasPositivo(r, i, "am",ps.get(i).getText());
                    
                    comprobarRespuestasNegativo(r, i, "am",ps.get(i).getText());
                    
                }
            }
        }
        textoCorrectas.setText("correctas: " + correctas + "/16");
        textoIncorrectas.setText("incorrectas: " + incorrectas + "/16");
        textoNota.setText("NOTA: " + nota);

    }//GEN-LAST:event_botonCorregirActionPerformed

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        nota = 0.0;
        correctas = 0;
        incorrectas = 0;
        es.forEach(e -> e.setText(""));
        cs.forEach(c -> {
            c.setVisible(false);
            c.setIcon(null);
        });
        textoCorrectas.setText("");
        textoIncorrectas.setText("");
        textoNota.setText("");
    }//GEN-LAST:event_botonReiniciarActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void cr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void cr51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr51ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c8ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       desktop.setBounds(this.getX(), this.getY(), this.getWidth(), this.getHeight());
    }//GEN-LAST:event_formWindowStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ToBeNegative e=new ToBeNegative();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r52ActionPerformed

    private void cr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr6ActionPerformed

    private void r51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r51ActionPerformed

    private void cr52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr52ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c7ActionPerformed

    private void cr7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr7ActionPerformed

    private void cr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr8ActionPerformed

    private void e9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e9ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c9ActionPerformed

    private void cr9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr9ActionPerformed

    private void e10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e10ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void cr10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr10ActionPerformed

    private void cr11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cr11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToBeQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToBeQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToBeQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToBeQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToBeQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCorregir;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton c1;
    private javax.swing.JButton c10;
    private javax.swing.JButton c11;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JButton cr1;
    private javax.swing.JButton cr10;
    private javax.swing.JButton cr11;
    private javax.swing.JButton cr2;
    private javax.swing.JButton cr3;
    private javax.swing.JButton cr4;
    private javax.swing.JButton cr51;
    private javax.swing.JButton cr52;
    private javax.swing.JButton cr6;
    private javax.swing.JButton cr7;
    private javax.swing.JButton cr8;
    private javax.swing.JButton cr9;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e10;
    private javax.swing.JTextField e11;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JTextField e8;
    private javax.swing.JTextField e9;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel label;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r10;
    private javax.swing.JTextField r11;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r51;
    private javax.swing.JTextField r52;
    private javax.swing.JTextField r6;
    private javax.swing.JTextField r7;
    private javax.swing.JTextField r8;
    private javax.swing.JTextField r9;
    private javax.swing.JLabel textoCorrectas;
    private javax.swing.JLabel textoIncorrectas;
    private javax.swing.JLabel textoNota;
    // End of variables declaration//GEN-END:variables

    public void comprobar(JTextField e, int j, String verbo) {
        cs.get(j).setVisible(true);
            
        if (e.getText().equalsIgnoreCase(verbo) || e.getText().equalsIgnoreCase("'".concat(verbo))
                || e.getText().equalsIgnoreCase("`".concat(verbo))
                || e.getText().equalsIgnoreCase("´".concat(verbo))) {
            
            cs.get(j).setIcon(new ImageIcon(getClass().getResource("/imagenes/tildeVerde2.png")));
            correctas++;
            nota+=puntajeXEjer; 
        } else {
            cs.get(j).setIcon(iconNegativo);
            incorrectas++;
        }
    }

    private void comprobarRespuestasPositiva(JTextField r, int i, String verbo,String nombre) {
        String pronombre=r.getText().substring(ICONIFIED, WIDTH);
        String verboR=
        if(a.contains(verbo.toLowerCase()) || a)
    }
}
